model:
  task: classification
  name: custom-CCNet
  kwargs: {} 
  num_classes: 5
  pretrained: False
  backbone_freeze: False
  bn_freeze: False
  bn_freeze_affine: False
  attention_pool: False
data:
  root: data/data_val  
  nw: 4 
  train:
    bs: 32 
    common_aug: null 
    class_aug: null 

    augment: 
      random_choice: 
      - random_color_jitter:
            prob: 0.5
            brightness: 0.1
            contrast: 0.1
            saturation: 0.1
            hue: 0.1
      - random_cutout:
            n_holes: 4
            length: 80 
            ratio: 0.3
            prob: 0.1
      - random_horizonflip:
            p: 0.5
      - random_gaussianblur:
            prob: 0.1
            kernel_size: 7
      pad2square: no_params
      random_crop_and_resize:
        scale: [0.2, 1.0]
        size: 480
      to_tensor: no_params 
    aug_epoch: 20 
  val:
    bs: 32
    augment:
        pad2square: no_params
        resize:
          size: 480
        to_tensor: no_params
hyp:
  epochs: 100
  lr0: 0.008 
  lrf_ratio: null 
  momentum: 0.937
  weight_decay: 0.0005
  warmup_momentum: 0.8
  warm_ep: 1
  loss:
    joint_ce_center: True
  label_smooth: 0.1
  strategy:
    prog_learn: False
    mixup:
      - 0.1 
      - [0, 20]
    focal: 
      - False
      - 0.25
      - 1.5
    ohem:
      - False
      - 8 
      - 0.7 
      - 255
  optimizer: 
    - sgd 
    - False 
  scheduler: cosine_with_warm 